sitaji/urls.py
from django.urls import path
from . import views

app_name ="sitaji"

urlpatterns = [
    path('', views.indexView.as_view(), name="index"),
    path('<int:pk>', views.detailView.as_view(), name ="detail"),
    path('add-student', views.studentAdd.as_view(), name ="add-student"),
    path('register', views.UserFormView.as_view(), name ="register"),
    path('<int:pk>/update', views.studentUpdate.as_view(), name ="update-student"),
    path('<int:pk>/delete', views.studentDelete.as_view(), name ="delete-student")
]
	

xyz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings   # this is useful for importing media settings
from django.conf.urls.static import static  # this is for static files
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('sitaji.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sitaji/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class student(models.Model):
    name = models.CharField(max_length=50)
    fname = models.CharField(max_length = 50)
    email = models.CharField(max_length= 100)
    intro = models.TextField(default="")
    image = models.FileField()

    def get_absolute_url(self):
    	return reverse('sitaji:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.name + ' - ' + self.fname

sitaji/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username','email','password']

sitaji/views.py
# from django.shortcuts import render,get_object_or_404
# from .models import student

# # Create your views here.
# def index(request):
#     all_student = student.objects.all()
#     return render(request,'index.html',{"students":all_student})

# def detail(request,student_id):
# 	# single_student = student.objects.get(pk=student_id)
# 	single_student = get_object_or_404(student,pk=student_id)
# 	return render(request,'detail.html',{"student":single_student})

from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
#import required for user login 
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.views import View
# import required for mixins
from django.contrib.auth.mixins import LoginRequiredMixin
# import required for delete object
from django.urls import reverse_lazy

from .models import student
from .forms  import UserForm

class indexView(generic.ListView):
	template_name = 'sitaji/index.html'
	context_object_name ="students"
	paginate_by = 6
		
	def get_queryset(self):
		return student.objects.all()

class detailView(generic.DetailView):
	model = student 
	template_name = 'sitaji/detail.html'

class studentAdd(LoginRequiredMixin,CreateView):
	model = student
	fields = ['name','fname','email','image']
	login_url = '/login'

class studentUpdate(LoginRequiredMixin,UpdateView):
	model = student
	fields = ['name','fname','email','image']
	login_url = '/login'

class studentDelete(DeleteView):
	model = student
	success_url = reverse_lazy('sitaji:index')

class UserFormView(View):
	form_class = UserForm
	template_name = 'sitaji/registration_form.html'

	def get(self,request):
		form = self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form = self.form_class(request.POST)

		if form.is_valid():
			user = form.save(commit=False)
			#cleaned_normalized data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#authenticate
			user = authenticate(username=username,password=password)

			if user is not None:
				if user.is_active:
					login(request,user)
					return redirect('sitaji:index')
		
		return render(request,self.template_name,{'form':form})

sitaji/templates/sitaji/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/mat.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mat.css' %}" />
    <title>{% block title %} Base template for sitaji app{% endblock %}</title>
  </head>
  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="{% url 'sitaji:index' %}" class="brand-logo right">Home</a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><a href="{% url 'sitaji:add-student' %}">Add Student</a></li>
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
      </div>
    </nav>

    {% block body %} {% endblock %}

    <div style="padding:20px 0px;"></div>
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Footer Content</h5>
            <p class="grey-text text-lighten-4">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vel
              dolorem asperiores provident voluptatum enim id. Velit quos,
              minima nisi sunt voluptate inventore obcaecati cum dicta, modi,
              repellendus natus! Consectetur, iusto!
            </p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li>
                <a class="grey-text text-lighten-3" href="{% url 'login' %}">
                  {% if not user.is_authenticated %} Login {% else %} Logout {% endif %}
                </a>
              </li>

              <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          © 2014 Copyright Text
          <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
      </div>
    </footer>
  </body>
</html>

sitaji/templates/sitaji/detail.html
{% extends 'sitaji/base.html' %}
{% block title %} Student information- {{student.name}}  {% endblock %}
{% block body %}
<div class="container">
	<h2>Single Studnet Details :{{student.id}}</h2>

	<img src="{{student.image.url}}" alt="">
	<p>
		Name : {{student.name}} <br>
		father name : {{student.fname}} <br/>
		email ID  : {{student.email}}
	</p>
	<a href="{% url 'sitaji:index' %}">Back to Home Page</a>
</div>
{% endblock %}

sitaji/templates/sitaji/form-template.html
{% for field in form %}
	<div class="error-msg">
		<span class="text-danger small">{{field.errors}}</span>
	</div>
	<label for='{{field.label_tag}}'>{{field.label_tag}}</label>
	{{field}}
{% endfor %}

sitaji/templates/sitaji/index.html
{% extends 'sitaji/base.html' %}
{% block title %} My app -Home Page {% endblock %}
{% block body %}
<div class="container">
    <h1>My Student app</h1>
    <div class="row">
    {% for student in students %}
        <div class="col s4" style="margin-bottom: 10px;">
             <a href="{% url 'sitaji:detail' student.id %}"><img class="responsive-img"  src="{{student.image.url}}" alt="student Photo" ></a> <br/>
             Student Name  : {{student.name}} <br/>
             <a class="btn" href="{% url 'sitaji:delete-student' student.id %}">Delete</a>
             <a class="btn" href="{% url 'sitaji:update-student' student.id %}">Update</a>
        </div>
    {% endfor %}
    </div>
    {# .... **Now the pagination section** .... #}
    <div class="container"></div>
        {% include 'sitaji/pagination.html' %}
    </div>
</div>
{% endblock %}

sitaji/templates/sitaji/pagination.html
{% if is_paginated %}
<ul class="pagination">
{% if page_obj.has_previous %}
    <li class="waves-effect">
        <a  href="?page={{ page_obj.previous_page_number }}">Previous</a>
    </li>
{% endif %}
    <li class="waves-effect">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </li>
{% if page_obj.has_next %}
    <li class="waves-effect">
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
{% endif %}
</ul>
{% else %}
    <h3>Your File Exam</h3>
    <p>File not yet available</p>
{% endif %}

sitaji/templates/sitaji/registration_form.html
{% extends 'sitaji/base.html' %}
{% block title %} Create New User {% endblock %}
{% block body %}
	<div class="container">
	<h1>Login/Create New User</h1>
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% include 'sitaji/form-template.html' %}
		<button type="submit"> Submit</button>
	</form>
	</div>
{% endblock %}

sitaji/templates/sitaji/student_confirm_delete.html
<h1>Delete Confirmation</h1>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

sitaji/templates/sitaji/student_form.html
{% extends 'sitaji/base.html' %}
{% block title %} Add new Student {% endblock %}
{% block body %}
	<div class="container">
	<h1>Add New Student</h1>
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% include 'sitaji/form-template.html' %}
		<button class="btn waves-effect waves-light" type="submit"> Submit</button>
	</form>
	</div>
{% endblock %}